CREATE TYPE "public"."Gender" AS ENUM('Male', 'Female', 'Other');--> statement-breakpoint
CREATE TABLE "BookCons" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"otpCode" text NOT NULL,
	"otpCodeCreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"photo" text NOT NULL,
	"name" varchar(64) NOT NULL,
	"fatherName" varchar(64) NOT NULL,
	"grandFatherName" varchar(64) NOT NULL,
	"gender" "Gender" NOT NULL,
	"dateOfBirth" timestamp with time zone NOT NULL,
	"placeOfBirth" text NOT NULL,
	"height" real NOT NULL,
	"eyeColor" text NOT NULL,
	"hairColor" text NOT NULL,
	"occupation" text NOT NULL,
	"region" text NOT NULL,
	"country" text NOT NULL,
	"zone" text NOT NULL,
	"city" text NOT NULL,
	"woreda" text NOT NULL,
	"streetName" text NOT NULL,
	"kebele" text NOT NULL,
	"phoneNumber" text NOT NULL,
	"houseNo" text NOT NULL,
	"poBox" text,
	"email" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "BookCons_otpCode_unique" UNIQUE("otpCode"),
	CONSTRAINT "BookCons_email_unique" UNIQUE("email")
);
